### ISSUE TITLE
Adding archaeal specific marker genes?

### ISSUE THREAD

**Issue by Kohtzanth** [liu-congcong/MetaDecoder#11]
Hello,

I was wondering if it might be possible to expand the set of 107 bacterial marker genes used in the current version to also include archaeal marker genes? like those used by the GTDB or found here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0077033
This might improve the use of metadecoder in samples with mixed archaea and bacteria.

Thank you

**Comment by liu-congcong** [comment]
Hello Kohtzanth,

Thanks for the suggestion.
A part of the bacterial markers in MetaDecoder is also present in archaea. Although it is not very accurate, it is possible to classify archaea. The seed selection model in the current version of MetaDecoder limits the possibility to extend the marker gene set.
I already have new plans, as you mentioned. This may take a while and luck.
Finally thank you very much for your advice and I hope that the imperfect program will give you perfect results.

Best,

Cong-Cong
