### ISSUE TITLE
Generate coverage file using bamfiles

### ISSUE THREAD

**Issue by ziyewang** [liu-congcong/MetaDecoder#3]
Hi,

I only have bam files of the samples. Can I use them to generate a coverage file to run MetaDecoder? Thanks.

Best,
Ziye

**Comment by liu-congcong** [comment]
Thank you for using MetaDecoder, Yes, of course.
Suppose you have several BAM files based on the same ASSEMBLY file, e.g. 1.BAM, 2.BAM, etc.

Step 1, convert all BAM files to SAM files using Samtools:
samtools view -@ 10 -h -o 1.SAM 1.BAM
samtools view -@ 10 -h -o 2.SAM 2.BAM

Step 2, get the coverage file:
metadecoder coverage -s 1.SAM 2.SAM -o COVERAGE

Step3, get the seed file:
metadecoder seed -f ASSEMBLY -o SEED

Step4, run MetaDecoder for clustering contigs:
metadecoder cluster -f ASSEMBLY -s SEED -c COVERAGE -o METADECODER

**Comment by liu-congcong** [comment]
Suppose you have several assembly files, e.g. 1.ASSEMBLY, 2.ASSEMBLY. And the corresponding BAM files, e.g. 1.BAM, 2.BAM. Please run MetaDecoder separately for 1.ASSEMBLY, 1.BAM and 2.ASSEMBLY, 2.BAM.

**Comment by ziyewang** [comment]
Thanks for your response.
