### ISSUE TITLE
Ask help on the installation of the MetaDecoder

### ISSUE THREAD

**Issue by B-1991-ing** [liu-congcong/MetaDecoder#5]
Dear MetaDecoder support team,

I emailed our HPC admin to install the MetaDecoder, but this is their reply. Could you update some dependencies for us?

<img width="611" alt="Screenshot 2022-07-12 at 14 17 56" src="https://user-images.githubusercontent.com/54441633/178487807-9621bb00-b8f6-4e64-89b0-786b292ab57e.png">

Best,

Bing

**Comment by liu-congcong** [comment]
Thank you very much for using MetaDecoder.
Once I fully verify the usability of MetaDecoder, I will remove the version restrictions of the dependencies.
But until then, you may need to do as follows:

1. git clone https://github.com/liu-congcong/MetaDecoder.git
3. cd MetaDecoder
4. Edit the setup.py file:
    Line 31: 'numpy == 1.18.5' -> 'numpy'
    Line 32: 'scipy == 1.5.4' -> 'scipy'
    Line 33: 'scikit-learn == 0.23.2' -> 'scikit-learn'
5. python3 setup.py install
6. pip3 install numpy scikit-learn scipy threadpoolctl

It should be noted that in step 3, please just remove the version restriction, please do not change the line indentation.
If you have any difficulties with the installation, please contact me.

**Comment by liu-congcong** [comment]
I have also uploaded the MetaDecoder here (https://drive.google.com/drive/folders/10LVMoc1txmyyKTig6AYly-BjVqSrL4pS?usp=sharing).
Just download and install it, please be careful not to change the file name.
pip3 install metadecoder-1.0.13-py3-none-any.whl

**Comment by B-1991-ing** [comment]
Hi congcong,

Thank you very much for your quick reply. 

I've already sent your response to our admin and I am not sure which way he would choose.

Best,

Bing
